# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 113789cde4f2c71f6b89e13b41a4a9a25dc917704f72afaf465d94af4c0157027c180361a5f3420a81ced9980bf25e7b4c98ad8328598be0f910f70c9a2f140b

test:
  secret_key_base: 601f255d7c189232eaf1beec9b4c73e82fb19aa3cd67ec4489717e98140612cbfcdabca2417346937b6d8873d0b3fbe8de1cdcda080a951a59d82331b0618b55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
