# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 019bd7bcb011131a9363fad0564d7f92d7c3aa6436e871ae168d7e8001eabe53dbb0394db5d7596d8321e3b4c5f737231e3d15189b451b95c8728edf2baa5f2c

test:
  secret_key_base: 21ac787de3de27704c31bc1cf8e7f91cc9765750141fc91372549fb068a552ab5e7b489a4ebd7929fedcd8d39c49220f2714bbadced9a19c1b808e1414be81bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
